### ISSUE TITLE
Radar Data-Block

### ISSUE THREAD

**Issue by jamesg31** [jamesg31/TowerGame#5]
Add more data to the radar block depending on if it is on the ASDEX or radar. Needs info like speed, altitude ect.

**Comment by jamesg31** [comment]
I was thinking of maybe trying to find a way to get the Asdex and Radar class actually deal with determining what needs to be shown to the player as different data will be shown to each player, but I am not entirely sure how to do this as I guess we would want to render the text outside of the Aircraft class? Maybe have a function in the aircraft class to add data to the block? I am not really sure - will have to think about it.

**Comment by AdamJCavanaugh** [comment]
I'm working on this a little as part of issue 6... just getting my feet wet, so don't feel bad if you decide on something different... or maybe I can't even get my idea to work. :P
