### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by jamesg31** [jamesg31/TowerGame#6]
Altitude will need to be implemented.

**Comment by AdamJCavanaugh** [comment]
At this point, that would be be as simple as adding an attribute to the Aircraft class, then updating the update method to set the altitude when called, right? We'll need to plan to handle climb/descend speed (change over time), which is also missing for heading and speed currently, right?

Do you just want the attribute/method added/updated for now or do you want change over time added for 1/both? If so, it seems that the position is only updated when "not scene," meaning viewing the airport pauses airplanes. Is this intended?

**Comment by jamesg31** [comment]
Yep, this is a pretty simple one. Not sure if it will mess up speed (currently the speed is ground speed not airspeed) I will need to look at the physics of it. Might just ignore this fact for now and push it further down the pipeline.

I think I get what you are saying here. When you view the asdex (airport map) the aircraft should still all update. aircraft.update() should update both the asdex_x and y, and radar_x and y regardless of which scene you have open. This is probably gonna change since it is pretty inefficient and kinda annoying. It really should be just update an aircraft location, and the radar and asdex classes should deal with individually converting the lat lon to pixels. Reference issue #4 for that change. 

I also made issue #7 for general changing of attributes. Probably didnt need this to be a separate issue but yeah.
